### ISSUE TITLE
No corona i Estonia

### ISSUE THREAD

**Issue by sonnichjensen** [okestonia/koroonakaart#289] opened 2022-08-01 14:13 UTC
I see that all numbers are 0.
There is no more Corona in Estonia :D

**Comment by neuroactive** [comment] 2022-08-01 19:11
Hi, unfortunately there is a problem with the source data. Please see my last comment here, which describes the problem and my attempts at finding a solution:

https://github.com/okestonia/koroonakaart/issues/280

I am closing this issue as it's essentially a duplicate of that one.

**Closed as completed by neuroactive** 2022-08-01 19:11 UTC
